## BASICS ##
export ZSH_STUFF="${HOME}/.dotfiles/zsh"

# oh-my-zsh
source "${ZSH_STUFF}/oh-my-zsh-config.zsh"

# hh (shell history)
export HISTFILE=~/.zsh_history  # ensure history file visibility
export HH_CONFIG=hicolor        # get more colors
bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)

# Path
source "${ZSH_STUFF}/path.zsh"
# Aliases
source "${ZSH_STUFF}/aliases.zsh"
# Functions
source "${ZSH_STUFF}/functions.zsh"

# OnSite stuff
source "${ZSH_STUFF}/lssupport/onsite/server.zsh"
source "${ZSH_STUFF}/lssupport/onsite/api.zsh"
# Support Ops stuff
source "${ZSH_STUFF}/lssupport/supportops/homestead.zsh"

# iTerm2 Shell Integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Virtual Go
# command -v vg >/dev/null 2>&1 && eval "$(vg eval --shell zsh)"

# Dad joke for lulz
# cowsay $(curl -s -H "Accept: text/plain" https://icanhazdadjoke.com/; echo)

# Ruby
if [ $(command -v rbenv) ]; then
    eval "$(rbenv init -)"
fi

# zcli autocomplete setup
ZCLI_AC_ZSH_SETUP_PATH=/Users/james.ratcliffe/Library/Caches/@zendesk/zcli/autocomplete/zsh_setup && test -f $ZCLI_AC_ZSH_SETUP_PATH && source $ZCLI_AC_ZSH_SETUP_PATH;